name       : ipset
version    : '7.15'
release    : 2
source     :
    - https://ipset.netfilter.org/ipset-7.15.tar.bz2 : 0a5545aaadb640142c1f888d366a78ddf8724799967fa20686a70053bd621751
license    : GPL-2.0-or-later
component  : security
homepage   : https://ipset.netfilter.org/
summary    : Tool to manage IP sets in the kernel
description: |
    IP sets are a framework inside the Linux kernel, which can be administered by the ipset utility. Depending on the type, an IP set may store IP addresses, networks, (TCP/UDP) port numbers, MAC addresses, interface names or combinations of them in a way, which ensures lightning speed when matching an entry against a set.
builddeps  :
    - pkgconfig(libmnl)
setup      : |
    %configure --disable-static \
        --with-kmod=no
build      : |
    %make
install    : |
    %make_install
