name       : ipset
version    : 6.30
release    : 1
source     :
    - http://ipset.netfilter.org/ipset-6.30.tar.bz2 : 65bfa43fec3d51a6b4012f3d7e4b93a748df9b71b6cd6c53adbec8083e804a31
license    : GPL-2.0
component  : security
summary    : Tool to manage IP sets in the kernel
description: |
    Tool to manage IP sets in the kernel
builddeps  :
    - pkgconfig(libmnl)
setup      : |
    %configure --disable-static \
               --with-kmod=no
build      : |
    %make
install    : |
    %make_install
